file_format: "1"
id: ferris_oled
name: Ferris OLED
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - ferris_oled_left
  - ferris_oled_right
